
-- pgsqlds2_create_db.sql: DVD Store Database Version 2.1 Build Script - Postgres version
-- Copyright (C) 2011 Vmware, Inc. 
-- Last updated 2/13/11
-- Tables

CREATE TABLE CUSTOMERS
  (
  CUSTOMERID SERIAL PRIMARY KEY, 
  FIRSTNAME VARCHAR(50) NOT NULL, 
  LASTNAME VARCHAR(50) NOT NULL, 
  ADDRESS1 VARCHAR(50) NOT NULL, 
  ADDRESS2 VARCHAR(50), 
  CITY VARCHAR(50) NOT NULL, 
  STATE VARCHAR(50), 
  ZIP VARCHAR(9), 
  COUNTRY VARCHAR(50) NOT NULL, 
  REGION INTEGER NOT NULL,
  EMAIL VARCHAR(50),
  PHONE VARCHAR(50),
  CREDITCARDTYPE INTEGER NOT NULL,
  CREDITCARD VARCHAR(50) NOT NULL, 
  CREDITCARDEXPIRATION VARCHAR(50) NOT NULL, 
  USERNAME VARCHAR(50) NOT NULL, 
  PASSWORD VARCHAR(50) NOT NULL, 
  AGE INTEGER, 
  INCOME INTEGER,
  GENDER VARCHAR(1) 
  )
  ;

  
CREATE TABLE ORDERS
  (
  ORDERID SERIAL PRIMARY KEY, 
  ORDERDATE DATE NOT NULL, 
  CUSTOMERID INTEGER, 
  NETAMOUNT NUMERIC NOT NULL, 
  TAX NUMERIC NOT NULL, 
  TOTALAMOUNT NUMERIC NOT NULL,
  FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID)
  )
  ; 


CREATE TABLE CATEGORIES
  (
  CATEGORY SERIAL PRIMARY KEY, 
  CATEGORYNAME VARCHAR(50) NOT NULL  
  )
  ;
   
  
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (1,'Action');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (2,'Animation');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (3,'Children');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (4,'Classics');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (5,'Comedy');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (6,'Documentary');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (7,'Drama');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (8,'Family');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (9,'Foreign');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (10,'Games');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (11,'Horror');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (12,'Music');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (13,'New');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (14,'Sci-Fi');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (15,'Sports');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (16,'Travel');
  
CREATE TABLE PRODUCTS
  (
  PROD_ID SERIAL PRIMARY KEY, 
  CATEGORY INTEGER NOT NULL, 
  TITLE TEXT NOT NULL, 
  ACTOR TEXT NOT NULL, 
  PRICE NUMERIC NOT NULL, 
  SPECIAL INTEGER,
  COMMON_PROD_ID INTEGER NOT NULL, 
  FOREIGN KEY(CATEGORY) REFERENCES CATEGORIES(CATEGORY)
  )
  ;

  
CREATE TABLE CUST_HIST
  (
  CUSTOMERID INTEGER NOT NULL, 
  ORDERID INTEGER NOT NULL, 
  PROD_ID INTEGER NOT NULL,
  FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID),
  FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID), 
  FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID)
  )
  ;
  
CREATE TABLE ORDERLINES
  (
  ORDERLINEID INTEGER NOT NULL, 
  ORDERID INTEGER NOT NULL, 
  PROD_ID INTEGER NOT NULL, 
  QUANTITY INTEGER NOT NULL, 
  ORDERDATE DATE NOT NULL,
  FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID), 
  FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID)
  )
  ; 

CREATE TABLE INVENTORY
  (
  PROD_ID INTEGER NOT NULL PRIMARY KEY,
  QUAN_IN_STOCK INTEGER NOT NULL,
  SALES INTEGER NOT NULL,
  FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID)
  ) 
  ;
   
  
CREATE TABLE REORDER
  (
  PROD_ID INTEGER NOT NULL,
  DATE_LOW DATE NOT NULL,
  QUAN_LOW INTEGER NOT NULL,
  DATE_REORDERED DATE,
  QUAN_REORDERED INTEGER,
  DATE_EXPECTED DATE,
  FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID)
  )
  ;

