CREATE VIEW VIEW_USER_INFORMATION (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE)AS
SELECT CAST(U.USER_ID AS VARCHAR2(100)), U.FIRST_NAME, U.LAST_NAME, CAST(U.YEAR_OF_BIRTH AS NUMBER(38)),
CAST(U.MONTH_OF_BIRTH AS NUMBER(38)), CAST(U.DAY_OF_BIRTH AS NUMBER(38)), U.GENDER,
C2.CITY_NAME, C2.STATE_NAME, C2.COUNTRY_NAME, C1.CITY_NAME, C1.STATE_NAME, C1.COUNTRY_NAME, 
P.INSTITUTION, CAST(E.PROGRAM_YEAR AS NUMBER(38)), CAST(P.CONCENTRATION AS CHAR(100)), P.DEGREE
FROM USERS U 
LEFT JOIN USER_HOMETOWN_CITY UHC ON U.USER_ID=UHC.USER_ID
LEFT JOIN CITIES C1 ON UHC.HOMETOWN_CITY_ID=C1.CITY_ID
LEFT JOIN USER_CURRENT_CITY UCC ON U.USER_ID=UCC.USER_ID
LEFT JOIN CITIES C2 ON UCC.CURRENT_CITY_ID=C2.CITY_ID
LEFT JOIN EDUCATION E ON U.USER_ID=E.USER_ID
LEFT JOIN PROGRAMS P ON E.PROGRAM_ID=P.PROGRAM_ID;





CREATE VIEW VIEW_ARE_FRIENDS (USER1_ID, USER2_ID) AS
SELECT CAST(USER1_ID AS VARCHAR2(100)), CAST(USER2_ID AS VARCHAR2(100))
FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION (ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK) AS 
SELECT A.ALBUM_ID, CAST(A.ALBUM_OWNER_ID AS VARCHAR2(100)), A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME,
A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, PH.PHOTO_ID, PH.PHOTO_CAPTION, PH.PHOTO_CREATED_TIME, 
PH.PHOTO_MODIFIED_TIME, PH.PHOTO_LINK
FROM PHOTOS PH
INNER JOIN ALBUMS A ON PH.ALBUM_ID=A.ALBUM_ID;

CREATE VIEW VIEW_TAG_INFORMATION(PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE) AS
SELECT TAG_PHOTO_ID, CAST(TAG_SUBJECT_ID AS VARCHAR2(100)), TAG_CREATED_TIME, TAG_X, TAG_Y
FROM TAGS; 

CREATE VIEW VIEW_EVENT_INFORMATION(EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_LOCATION, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME, EVENT_END_TIME) AS
SELECT CAST(EV.EVENT_ID AS VARCHAR2(100)), CAST(EV.EVENT_CREATOR_ID AS VARCHAR2(100)), EV.EVENT_NAME, EV.EVENT_TAGLINE, 
EV.EVENT_DESCRIPTION, EV.EVENT_HOST, EV.EVENT_TYPE, EV.EVENT_SUBTYPE, EV.EVENT_LOCATION, C.CITY_NAME, C.STATE_NAME, 
C.COUNTRY_NAME, EV.EVENT_START_TIME, EV.EVENT_END_TIME
FROM USER_EVENTS EV
LEFT JOIN CITIES C ON EV.EVENT_CITY_ID=C.CITY_ID;
