--use for dropping table
--ALTER TABLE ALBUM DROP CONSTRAINT ALBUMS_PHOTOS;
--ALTER TABLE PHOTOS DROP CONSTRAINT PHOTOS_ALBUMS;
DROP SEQUENCE PRO_SEQUENCE;

DROP SEQUENCE CITIES_SEQUENCE;

DROP TRIGGER PRO_TRIGGER;

DROP TRIGGER CITIES_TRIGGER;

DROP TRIGGER FRIENDS_TRIGGER;

DROP TABLE TAGS;

DROP TABLE ALBUMS CASCADE CONSTRAINTS;

DROP TABLE PHOTOS CASCADE CONSTRAINTS;

DROP TABLE PARTICIPANTS;

DROP TABLE USER_EVENTS;

DROP TABLE EDUCATION;

DROP TABLE PROGRAMS;

DROP TABLE MESSAGE;

DROP TABLE USER_HOMETOWN_CITY;

DROP TABLE USER_CURRENT_CITY;

DROP TABLE CITIES;

DROP TABLE FRIENDS;

DROP TABLE USERS;
