SELECT* from VIEW_USER_INFORMATION 
MINUS
SELECT* from keykholt.PUBLIC_USER_INFORMATION;

SELECT* from keykholt.PUBLIC_USER_INFORMATION
MINUS 
SELECT* from VIEW_USER_INFORMATION; 


SELECT*FROM VIEW_ARE_FRIENDS
MINUS 
SELECT*FROM keykholt.PUBLIC_ARE_FRIENDS;

SELECT*FROM keykholt.PUBLIC_ARE_FRIENDS
MINUS
SELECT*FROM VIEW_ARE_FRIENDS;



SELECT*FROM VIEW_TAG_INFORMATION
MINUS
SELECT*FROM keykholt.PUBLIC_TAG_INFORMATION;

SELECT*FROM keykholt.PUBLIC_TAG_INFORMATION
MINUS
SELECT*FROM VIEW_TAG_INFORMATION;




SELECT*FROM VIEW_PHOTO_INFORMATION
MINUS
SELECT*FROM keykholt.PUBLIC_PHOTO_INFORMATION;

SELECT*FROM keykholt.PUBLIC_PHOTO_INFORMATION
MINUS
SELECT*FROM VIEW_PHOTO_INFORMATION;





SELECT*FROM VIEW_EVENT_INFORMATION
MINUS
SELECT*FROM keykholt.PUBLIC_EVENT_INFORMATION;

SELECT*FROM keykholt.PUBLIC_EVENT_INFORMATION
MINUS
SELECT*FROM VIEW_EVENT_INFORMATION;
